### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by orp4** [CDCgov/opencdc#39]
FDNS-MS-CDA-Utils  

fdns-ms-cda-utils 

These two links seem to be broken and unable to access

**Comment by leebrian** [comment]
Thanks so much for finding this bug. This is fixed in commit https://github.com/CDCgov/opencdc/commit/18b753095a244c376cd4e09c26be80c82bd06ed2

Key an eye out on [Releases](https://github.com/CDCgov/opencdc/releases) to see when your change is deployed to open.cdc.gov.
