### ISSUE TITLE
coronavirus.gov hyperlink issues

### ISSUE THREAD

**Issue by fanfare** [CDCgov/opencdc#45]
I can't find any place to submit website issues on cdc.gov websites in general. My apologies if this is the wrong place for it.

On coronavirus.gov ie. https://www.cdc.gov/coronavirus/2019-ncov/index.html

The hyperlinks need to have the CSS property `display:inline-block`

Currently there is a gap in between the hyperlinks that is non-clickable. This might be an accessibility issue for some users.

Below is a demonstration of the issue. Thank you!

![awoefjaoiewfjawoief](https://user-images.githubusercontent.com/46735339/76562557-9b6f4a00-6473-11ea-97ce-74de6ee6a24c.gif)

**Comment by leebrian** [comment]
Thanks for the issue. A different group builds that site. They don’t have a GitHub project, but I’ve sent them an email with your report and information.

**Comment by leebrian** [comment]
While not my project, I think this is closed and the site has different behavior now.
